Project/Project/ViewModels/GunsListViewModel.cs
using Project.Data.Models;
using System.Collections.Generic;

namespace Project.ViewModels
{
    public class GunsListViewModel
    {
        public IEnumerable<Guns> allGuns { get; set; }
        public string gunsCategory { get; set; }
    }
}

Project/Project/ViewModels/HomeViewModel.cs
using Project.Data.Models;
using System.Collections.Generic;

namespace Project.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Guns> favGuns { get; set; }
    }
}

Project/Project/ViewModels/ShopGunsViewModel.cs
using Project.Data.Models;

namespace Project.ViewModels
{
    public class ShopGunsViewModel
    {
        public ShopGuns shopGuns { get; set; }

    }
}

Project/Project/Controllers/GunsController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Data.Interface;
using Project.Data.Models;
using Project.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Project.Controllers
{
    public class GunsController : Controller
    {
        private readonly IAllGuns _allGuns;
        private readonly IGunsCategory _gunsCategory;

        public GunsController(IAllGuns iAllGuns, IGunsCategory iGunsCategory)
        {
            _allGuns = iAllGuns;
            _gunsCategory = iGunsCategory;
        }
        [Route("Guns/List")]
        [Route("Guns/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Guns> guns = null;
            string gunsCategory = "";
            if(string.IsNullOrEmpty(category))
            {
                guns = _allGuns.Guns.OrderBy(guns => guns.id);
            }
            else
            {
                if(string.Equals("pistols",category, StringComparison.OrdinalIgnoreCase))
                {
                    guns = _allGuns.Guns.Where(g => g.Category.categoryName.Equals("Пистолеты")).OrderBy(guns => guns.id);
                    gunsCategory = "Пистолеты";
                }
                else if(string.Equals("snipers", category, StringComparison.OrdinalIgnoreCase))
                {
                    guns = _allGuns.Guns.Where(g => g.Category.categoryName.Equals("Снайперские винтовки")).OrderBy(guns => guns.id);
                    gunsCategory = "Снайперские винтовки";
                }

            }
            var gunsObj = new GunsListViewModel
            {
                allGuns = guns,
                gunsCategory = gunsCategory,
            };

            ViewBag.Title = "Страница с оружием";           
            return View(gunsObj);
        }
    }
}

Project/Project/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Data.Interface;
using Project.ViewModels;

namespace Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllGuns _gunsRep;
        
        public HomeController(IAllGuns gunRep)
        {
            _gunsRep = gunRep;
           
        }
        public ViewResult Index()
        {
            var homeGuns = new HomeViewModel
            {
                favGuns = _gunsRep.getFavGuns
            };
            return View(homeGuns);
        }
    }
}

Project/Project/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Data.Interface;
using Project.Data.Models;

namespace Project.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allorders;
        private readonly ShopGuns shopGuns;
        public OrderController(IAllOrders allorders, ShopGuns shopGuns)
        {
            this.allorders = allorders;
            this.shopGuns = shopGuns;
        }
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopGuns.listShopItems = shopGuns.getShopItems();
            if (shopGuns.listShopItems.Count == 0)
            {
                ModelState.AddModelError("","Нету товаров");
            }
            if (ModelState.IsValid)
            {
                allorders.createOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

Project/Project/Controllers/ShopGunsController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Data.Interface;
using Project.Data.Models;
using Project.Data.Repository;
using Project.ViewModels;
using System.Linq;

namespace Project.Controllers
{
    public class ShopGunsController : Controller
    {
        private readonly IAllGuns _gunsRep;
        private readonly ShopGuns _shopGuns;

        public ShopGunsController(IAllGuns gunRep, ShopGuns shopGuns)
        {
            _gunsRep = gunRep;
            _shopGuns = shopGuns;
        }
        public ViewResult Index()
        {
            var items = _shopGuns.getShopItems();
            _shopGuns.listShopItems = items;

            var obj = new ShopGunsViewModel
            {
                shopGuns = _shopGuns
            };

            return View(obj);
        }
        public RedirectToActionResult addToGuns(int id)
        {
            var item = _gunsRep.Guns.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopGuns.AddToGuns(item);
            }
            return RedirectToAction("Index");
        }
    }
}

Project/Project/Views/Guns/List.cshtml
        <h1>Все Оружия</h1>
        <h3>@Model.gunsCategory</h3>
  <div class="row mtr-5 mb-2">
        @{

        foreach (Guns guns in Model.allGuns)
        {
           @Html.Partial("AllGuns", guns)
        }
        }
        </div> 

Project/Project/Views/Home/Index.cshtml
@model HomeViewModel


        <h1>Лучшие Оружия</h1>       
  <div class="row mtr-5 mb-2">
        @{

        foreach (Guns guns in Model.favGuns)
        {
           @Html.Partial("AllGuns", guns)
        }
        }
        </div> 

Project/Project/Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control"/>
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
         <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-5">
                <input asp-for="surname" class="form-control"/>
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>
         <div class="form-group">
            <label asp-for="adress"></label>
            <div class="col-md-5">
                <input asp-for="adress" class="form-control"/>
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
        </div>
         <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control"/>
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
         <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control"/>
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>      
        <input class="btn btn-success" type="submit" value="Завершить заказ"/>
    </form>
</div>

Project/Project/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Project/Project/Views/Shared/AllGuns.cshtml
@model Guns

 <div class="col-lg-4">
                <img class="img-thumbnail" src="@Model.img" alt="@Model.name"/>
                <h2>@Model.name</h2>
                <p>@Model.shortDesc</p>
                <p>Цена: @Model.price.ToString("c")</p>
                <p><a class="btn btn-warning" asp-controller="ShopGuns" asp-action="addToGuns" asp-route-id="@Model.id">Добавить в корзину</a></p>
            </div>

Project/Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" >
    <link href="~/css/style.css" rel="stylesheet" type="text/css" >
</head>
<body>
    <header>
  <nav class="navbar navbar-expand-md navbar-dark  bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Guns</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Guns/List">Оружия</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Guns/List/pistols">Пистолеты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Guns/List/snipers">Снайперки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/ShopGuns/">Корзина</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>© 2021 Все права защищены · <a href="#">Соглашение</a></p>
  </footer>
    <script src ="~/js/bootstrap.min.js"></script>
</body>
</html>

Project/Project/Views/ShopGuns/Index.cshtml
@model ShopGunsViewModel
<div class="container">
    @foreach(var el in Model.shopGuns.listShopItems)
    {
        <div class="alert alert.warning mt-3">
            <b>Оружия:</b>@el.guns.name<br />
            <b>Цена:</b>@el.guns.price.ToString("c")
         </div>
    }
    <hr />
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>